// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "navigation": {
    "home": "Home",
    "about": "About",
    "contact": "Contact"
  },
  "common": {
    "welcome": "Welcome to Next.js with Internationalization",
    "getStarted": "Get started by editing",
    "saveChanges": "Save and see your changes instantly",
    "deployNow": "Deploy now",
    "readDocs": "Read our docs",
    "learn": "Learn",
    "examples": "Examples",
    "goToNextjs": "Go to nextjs.org →"
  },
  "language": {
    "switch": "Switch Language",
    "english": "English",
    "turkish": "Turkish"
  }
};
export default messages;